version: '2'
services:
    name2key_endpoint:
        container_name: name2key_endpoint
        restart: always
        image: madpeter/secondlife_name2key_endpoint:latest
        expose:
            - 80:80
        ports:
            - 80:80
        links:
            - name2key_mysqli
        environment:
            DB_HOST: name2key_mysqli
            DB_DATABASE: 'name2keydb'
            DB_USERNAME: '{MySQLDBUser}'
            DB_PASSWORD: '{MySQLDBPW}'
            API_KEYS: 'setup'

    name2key_mysqli:
        container_name: name2key_mysqli
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '{MySQLRootPW}'
            MYSQL_USER: '{MySQLDBUser}'
            MYSQL_PASSWORD: '{MySQLDBPW}'
            MYSQL_DATABASE: 'name2keydb'
        volumes:
            - name2key-db:/var/lib/mysql_name2keydb
